language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  email:
    on_success: never
    on_failure: never

services:
  - mysql

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-text

after_script: