language: php

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

notifications:
  email:
    on_success: never
    on_failure: never
  slack: arcella:ri64SN1Ai5XTu5ms0oEz4MkK

services:
  - mysql

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
  - travis_retry vendor/bin/phpcs --config-set installed_paths vendor/escapestudios/symfony2-coding-standard
  - bin/console doctrine:database:create
  - bin/console doctrine:schema:create
  - bin/console hautelook_alice:doctrine:fixtures:load --no-interaction

script:
  - vendor/bin/phpunit -v --coverage-text
  - vendor/bin/phpcs src -v --standard=Symfony2

after_script:
