# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    register_user_handler:
        class: Arcella\Application\Handler\RegisterUserHandler
        arguments: ['@arcella.userbundle.user_repository', '@validator', '@event_dispatcher', '%arcella.security.salt_length%', '%arcella.security.salt_keyspace%']
        tags:
            - { name: command_handler, handles: Arcella\Domain\Command\RegisterUser }

    arcella.userbundle.doctrine.hash_password_listener:
        class: Arcella\UserBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }

    arcella.userbundle.user_repository:
        class: Arcella\UserBundle\Repository\DoctrineORMUserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Arcella\UserBundle\Entity\User

    arcella.security.login_form_authenticator:
        class: Arcella\UserBundle\Security\LoginFormAuthenticator
        autowire: true